import type { MapNode, NodeType } from '@/lib/map/types';
import type { FamilyName } from '@/lib/styles/tokens.generated';
import {
  availableNodeTypes,
  isCreatableType,
  soonNodeTypes,
} from '@/lib/nodes/registry';

/**
 * The local-first edit buffer.
 *
 * §14: "Autosave, debounced 800ms... No Save button. A Save button in a canvas
 * editor is a bug report waiting to happen."
 *
 * That makes the draft — not the server — the source of truth while editing.
 * Every command applies to the draft immediately and synchronously; the save
 * runs behind it. The user never waits for the network to see their own edit,
 * and an edit made offline is not lost.
 */

export interface DraftNode extends MapNode {
  /**
   * Free position, set by Alt+drag (§14). When absent the node snaps to its
   * angular slot, which is the default and the thing that keeps a map tidy.
   */
  freeX?: number;
  freeY?: number;
}

export interface MapDraft {
  id: string;
  title: string;
  /** Single hue for a user map's centre ring (§06 map spaces). */
  family: FamilyName;
  visibility: 'private' | 'link' | 'public';
  rootId: string;
  nodes: Record<string, DraftNode>;

  /**
   * Where this map came from, when it was generated by Link-to-Mind-Map (§12).
   *
   * On the map rather than on each node: every node in a generated map shares
   * one source, and storing the URL a hundred times to render the same chip is
   * the same string a hundred times. Absent on a hand-built map.
   */
  sourceUrl?: string;
  sourceTitle?: string;

  // ---- conflict fields -----------------------------------------------------
  /**
   * Incremented by the server on every accepted write. Sent back with the next
   * save; a mismatch means someone else changed the map and the save is
   * rejected rather than silently overwriting them.
   */
  version: number;
  updatedAt: string;

  // ---- local bookkeeping ---------------------------------------------------
  /** Node ids changed since the last successful save. */
  dirty: string[];
  /** True when map-level fields (title, family, visibility) changed. */
  metaDirty: boolean;
}

export type SaveStatus =
  | 'idle'
  | 'saving'
  | 'saved'
  /** The save failed but the buffer is intact — §08 screen 09 error state. */
  | 'error'
  /** Navigator reports offline. Edits keep working; the save waits. */
  | 'offline'
  /** Someone else changed the map. Needs a decision, not a retry. */
  | 'conflict';

/**
 * Node types, DERIVED from the registry rather than listed here.
 *
 * These were three hand-maintained lists that had to agree with a union in
 * `map/types.ts` and a label map inside `MetaList.tsx`. They now read from
 * `lib/nodes/registry`, so registering a type is the only edit needed — the
 * picker, the labels and the validation all follow.
 *
 * §14: types that are not ready still APPEAR in the picker, disabled. Showing
 * them communicates the ambition; badging them Soon stops it being a promise.
 */
export const MVP_NODE_TYPES: readonly NodeType[] = availableNodeTypes().map(
  (definition) => definition.id as NodeType,
);

export const SOON_NODE_TYPES: readonly NodeType[] = soonNodeTypes().map(
  (definition) => definition.id as NodeType,
);

export function isMvpType(type: NodeType): boolean {
  return isCreatableType(type);
}
