import 'server-only';
import { randomUUID } from 'node:crypto';
import type { Database } from 'better-sqlite3';
import { getDb } from '@/lib/db/client';
import type { AuthContext } from '@/lib/db/repo';
import { capabilitiesOnMap } from '@/lib/permissions/resolve';
import { MAX_DRIFT_MS, type Hlc } from './hlc';
import { applyAll, emptyState, type MapState, type Operation } from './crdt';

/**
 * The server side of offline sync.
 *
 * ── Two counters, two jobs ──────────────────────────────────────────────────
 *
 * Every operation carries a hybrid logical clock AND is assigned a per-map
 * sequence number by the server. They look redundant and are not:
 *
 *   the HLC        decides CONFLICTS. It is generated by the device, works
 *                  offline, and orders edits that never met.
 *
 *   the sequence   decides DELIVERY. It is assigned on arrival, in one place,
 *                  so "give me everything after 4,192" is a question with an
 *                  exact answer. A device cannot assign it — it has no idea
 *                  what other devices have sent.
 *
 * Conflating them is the classic mistake. Paginating by timestamp loses
 * operations whose clocks tie, and resolving conflicts by arrival order makes
 * the winner depend on network latency.
 *
 * ── Permission is checked on push, not replayed per operation ───────────────
 *
 * A batch belongs to one map and one actor, so `editNodes` is checked once for
 * the batch. Per-node grants are NOT consulted here, and that is a real limit
 * worth stating plainly: offline sync operates at map granularity. A person
 * denied one node of a map they can otherwise edit can push an operation
 * touching it. Closing that properly means shipping the grant set to the
 * device, which is a design problem rather than a missing `if`. It is recorded
 * in ADR-0011 rather than left for someone to discover.
 */

export interface StoredOp extends Operation {
  id: string;
  seq: number;
}

interface OpRow {
  id: string;
  seq: number;
  device_id: string;
  hlc_millis: number;
  hlc_count: number;
  kind: string;
  node_id: string;
  field: string;
  value: string;
  actor_id: string | null;
}

function hydrate(row: OpRow): StoredOp {
  let value: unknown = null;
  try {
    value = JSON.parse(row.value);
  } catch {
    value = null;
  }

  return {
    id: row.id,
    seq: row.seq,
    kind: row.kind as Operation['kind'],
    nodeId: row.node_id,
    field: row.field,
    value,
    clock: {
      millis: row.hlc_millis,
      count: row.hlc_count,
      deviceId: row.device_id,
    },
    actorId: row.actor_id,
  };
}

/** The most operations one push may carry. */
export const MAX_BATCH = 500;

export interface PushResult {
  ok: boolean;
  /** Operations actually written. A repeat writes none and is not an error. */
  accepted?: number;
  /** The map's sequence after the push. The client stores this. */
  seq?: number;
  error?: string;
}

const KINDS = new Set(['create_node', 'set_field', 'delete_node']);

/**
 * Accept a batch of operations from a device.
 *
 * ── Idempotent, because offline clients retry ───────────────────────────────
 *
 * A device that pushes, loses connectivity before the response, and pushes
 * again must not double-apply. The unique index on (map, device, clock, node,
 * field) makes the second write a no-op — `INSERT OR IGNORE` rather than
 * application-level deduplication, so it holds even if two requests race.
 */
export function push(
  ctx: AuthContext,
  input: {
    mapId: string;
    deviceId: string;
    ops: readonly Operation[];
  },
  db: Database = getDb(),
): PushResult {
  if (!ctx.userId) return { ok: false, error: 'Sign in first' };

  if (!capabilitiesOnMap(ctx, input.mapId, db).editNodes) {
    // 'Not found', like everywhere else: a refusal that confirms the map
    // exists is a refusal that tells an attacker where to look.
    return { ok: false, error: 'Not found' };
  }

  if (input.ops.length > MAX_BATCH) {
    return { ok: false, error: `Send at most ${MAX_BATCH} operations at a time` };
  }

  const deviceId = input.deviceId.slice(0, 80);
  if (!deviceId) return { ok: false, error: 'A device id is required' };

  const now = Date.now();

  return db.transaction((): PushResult => {
    const current = (
      db
        .prepare(
          'SELECT COALESCE(MAX(seq), 0) AS seq FROM sync_ops WHERE map_id = ?',
        )
        .get(input.mapId) as { seq: number }
    ).seq;

    let seq = current;
    let accepted = 0;

    for (const op of input.ops) {
      if (!KINDS.has(op.kind)) continue;
      if (!op.nodeId) continue;

      /*
       * A clock too far in the future is refused rather than stored.
       *
       * One device with a broken clock would otherwise poison the map
       * permanently: its timestamp wins every future conflict, and no later
       * edit from a correct clock can ever displace it. Refusing keeps the
       * damage on the device that is wrong.
       */
      if (op.clock.millis - now > MAX_DRIFT_MS) continue;

      // The device id in the clock must be the pushing device. Otherwise one
      // device can forge operations attributed to another, which breaks the
      // tie-break that makes the order total.
      if (op.clock.deviceId !== deviceId) continue;

      seq += 1;

      const changes = db
        .prepare(
          `INSERT OR IGNORE INTO sync_ops
             (id, map_id, seq, device_id, hlc_millis, hlc_count, kind,
              node_id, field, value, actor_id)
           VALUES (@id, @mapId, @seq, @deviceId, @millis, @count, @kind,
                   @nodeId, @field, @value, @actorId)`,
        )
        .run({
          id: randomUUID(),
          mapId: input.mapId,
          seq,
          deviceId,
          millis: Math.round(op.clock.millis),
          count: Math.round(op.clock.count),
          kind: op.kind,
          nodeId: op.nodeId.slice(0, 80),
          field: (op.field ?? '').slice(0, 60),
          value: JSON.stringify(op.value ?? null).slice(0, 20_000),
          actorId: ctx.userId,
        }).changes;

      if (changes > 0) accepted += 1;
      // A duplicate consumed no sequence number, so it is given back. Gaps
      // would be harmless but make "how far behind am I" misleading.
      else seq -= 1;
    }

    db.prepare(
      `INSERT INTO sync_devices (device_id, user_id, map_id, last_seq, last_seen_at)
       VALUES (@deviceId, @userId, @mapId, @seq, datetime('now'))
       ON CONFLICT(device_id, map_id) DO UPDATE SET
         last_seq = MAX(last_seq, excluded.last_seq),
         last_seen_at = datetime('now')`,
    ).run({ deviceId, userId: ctx.userId, mapId: input.mapId, seq });

    return { ok: true, accepted, seq };
  })();
}

export interface PullResult {
  ok: boolean;
  ops?: StoredOp[];
  /** The highest sequence in this response. The client stores it. */
  seq?: number;
  /** True when more remain — the client should pull again immediately. */
  more?: boolean;
  error?: string;
}

/**
 * Everything after a sequence number.
 *
 * Bounded, with `more` rather than an unbounded response. A device returning
 * from a month offline would otherwise ask for a response big enough to
 * exhaust the server's memory — and the client's.
 */
export function pull(
  ctx: AuthContext,
  input: { mapId: string; deviceId: string; after: number; limit?: number },
  db: Database = getDb(),
): PullResult {
  if (!capabilitiesOnMap(ctx, input.mapId, db).view) {
    return { ok: false, error: 'Not found' };
  }

  const limit = Math.min(MAX_BATCH, Math.max(1, input.limit ?? MAX_BATCH));

  const rows = db
    .prepare(
      `SELECT * FROM sync_ops WHERE map_id = ? AND seq > ?
        ORDER BY seq LIMIT ?`,
    )
    .all(input.mapId, Math.max(0, Math.round(input.after)), limit + 1) as OpRow[];

  // One extra row was requested purely to answer "is there more", without a
  // second COUNT query racing against a concurrent push.
  const more = rows.length > limit;
  const page = more ? rows.slice(0, limit) : rows;
  const ops = page.map(hydrate);

  if (ctx.userId && input.deviceId) {
    db.prepare(
      `INSERT INTO sync_devices (device_id, user_id, map_id, last_seq, last_seen_at)
       VALUES (@deviceId, @userId, @mapId, @seq, datetime('now'))
       ON CONFLICT(device_id, map_id) DO UPDATE SET
         last_seq = MAX(last_seq, excluded.last_seq),
         last_seen_at = datetime('now')`,
    ).run({
      deviceId: input.deviceId.slice(0, 80),
      userId: ctx.userId,
      mapId: input.mapId,
      seq: ops.length > 0 ? ops[ops.length - 1]!.seq : Math.max(0, input.after),
    });
  }

  return {
    ok: true,
    ops,
    seq: ops.length > 0 ? ops[ops.length - 1]!.seq : Math.max(0, input.after),
    more,
  };
}

/**
 * Fold the whole log into current state.
 *
 * For a device with nothing, and for verifying convergence — comparing this
 * with a client's own digest is how divergence is detected, and divergence is
 * the only way anyone ever discovers a sync bug.
 */
export function materialiseMap(
  ctx: AuthContext,
  mapId: string,
  db: Database = getDb(),
): MapState {
  if (!capabilitiesOnMap(ctx, mapId, db).view) return emptyState();

  const rows = db
    .prepare('SELECT * FROM sync_ops WHERE map_id = ? ORDER BY seq')
    .all(mapId) as OpRow[];

  return applyAll(emptyState(), rows.map(hydrate));
}

export interface DeviceRow {
  deviceId: string;
  mapId: string;
  lastSeq: number;
  label: string;
  lastSeenAt: string;
}

/** A person's devices, for a "sign this out" screen. */
export function devicesFor(ctx: AuthContext, db: Database = getDb()): DeviceRow[] {
  if (!ctx.userId) return [];

  const rows = db
    .prepare(
      `SELECT device_id, map_id, last_seq, label, last_seen_at
         FROM sync_devices WHERE user_id = ?
        ORDER BY last_seen_at DESC LIMIT 100`,
    )
    .all(ctx.userId) as {
    device_id: string;
    map_id: string;
    last_seq: number;
    label: string;
    last_seen_at: string;
  }[];

  return rows.map((row) => ({
    deviceId: row.device_id,
    mapId: row.map_id,
    lastSeq: row.last_seq,
    label: row.label,
    lastSeenAt: row.last_seen_at,
  }));
}

/** Forget a device. It re-syncs from zero if it comes back. */
export function forgetDevice(
  ctx: AuthContext,
  deviceId: string,
  db: Database = getDb(),
): { ok: boolean } {
  const changes = db
    .prepare('DELETE FROM sync_devices WHERE device_id = ? AND user_id = ?')
    .run(deviceId, ctx.userId).changes;

  return { ok: changes > 0 };
}

/**
 * Build an operation from a field change, for the server's own writes.
 *
 * The editor still saves through `repo.saveMap`, and this is how those saves
 * also become operations an offline device can receive. Without it the two
 * paths would diverge: edits made in the browser would be invisible to a
 * device syncing, which is the worst possible half-working state.
 */
export function operationFor(
  nodeId: string,
  field: string,
  value: unknown,
  clock: Hlc,
): Operation {
  return { kind: 'set_field', nodeId, field, value, clock };
}
